# Basic Python

## 1. Split this string

In [8]:
s = "Hi there Sam!"

In [54]:
s.split()




['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [13]:
planet = "Earth"
diameter = 12742

In [55]:
sentence = 'The diameter of {} is {} kilometers '.format(planet,diameter)
print(sentence)

The diameter of Earth is 12742 kilometers 


## 3. In this nest dictionary grab the word "hello"

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [56]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [57]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [58]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [60]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [62]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [44]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a= np.concatenate((a,b),axis=0)
print(a)


[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [63]:
import pandas as pd  
      
  
lists = [[1, 3], [2, 5],[6,8]]
  
# creating df object with columns specified    
df = pd.DataFrame(lists) 
print(df )

   0  1
0  1  3
1  2  5
2  6  8


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [64]:
import datetime

# The size of each step in days
day_delta = datetime.timedelta(days=1)


start_date = datetime.date(2023, 1, 1)
end_date = datetime.date(2023, 2, 11)

for i in range((end_date - start_date).days):
    print(start_date + i*day_delta)

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [46]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [65]:
import pandas as pd  
      
  
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
  
# creating df object with columns specified    
df = pd.DataFrame(lists) 
print(df )

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
